# Build as jupyterhub/singleuser
# Run with the DockerSpawner in JupyterHub

#FROM jupyter/scipy-notebook
FROM jupyter/datascience-notebook

MAINTAINER Project Jupyter <jupyter@googlegroups.com>

EXPOSE 8888

USER root
# fetch juptyerhub-singleuser entrypoint
RUN ln -sf /bin/bash /bin/sh
RUN wget -q https://raw.githubusercontent.com/jupyterhub/jupyterhub/0.6.1/scripts/jupyterhub-singleuser -O /usr/local/bin/jupyterhub-singleuser && \
    chmod 755 /usr/local/bin/jupyterhub-singleuser
RUN conda install -c conda-forge jupyterlab && \
    conda install jupyter_client && \
    jupyter serverextension enable --py jupyterlab --sys-prefix

ADD start-singleuser.sh /srv/singleuser/start-singleuser.sh

RUN echo "jovyan ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER jovyan

# lightning python
RUN pip3 install lightning-python
RUN source activate /opt/conda/envs/python2 && \
    pip install lightning-python && \
    source deactivate
# lightning R
RUN R -e "install.packages('LightningR', repos='http://cran.rstudio.com/')"


# smoke test that it's importable at least
RUN sh /srv/singleuser/start-singleuser.sh -h
CMD ["sh", "/srv/singleuser/start-singleuser.sh"]
