# Adapted from https://github.com/lightning-viz/lightning/blob/master/Dockerfile
FROM node:6

MAINTAINER Lighning Viz <info@lightning-viz.org>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY lightning/package.json /usr/src/app/
RUN npm install

COPY lightning /usr/src/app/

RUN npm run build
RUN npm run fetch-visualizations

ENV DEBUG lightning:*

EXPOSE 3000

CMD ["npm","start"]
